/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading: string
  intro?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type AuthorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'author'
}

export type Story = {
  _id: string
  _type: 'story'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  summary: string
  featuredImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  author: AuthorReference
  publishedDate: string
  featured?: boolean
  tags?: Array<string>
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  bio?: string
  avatar?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | AuthorReference
  | Story
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../web/app/utils/queries.ts
// Variable: homeQuery
// Query: {  "settings": *[_id == "siteSettings"][0]{ eyebrow, heading, intro },  "featured": *[_type == "story" && defined(slug.current) && defined(publishedDate) && featured == true] | order(publishedDate desc)[0...3]{    _id,    title,    "slug": slug.current,    summary,    publishedDate,    featured,    tags,    featuredImage{      ...,      "lqip": asset->metadata.lqip,      "dimensions": asset->metadata.dimensions    },    "authorName": author->name,    "readingTime": round(length(pt::text(body)) / 5 / 200)  },  "stories": *[_type == "story" && defined(slug.current) && defined(publishedDate)] | order(publishedDate desc){    _id,    title,    "slug": slug.current,    summary,    publishedDate,    featured,    tags,    featuredImage{      ...,      "lqip": asset->metadata.lqip,      "dimensions": asset->metadata.dimensions    },    "authorName": author->name,    "readingTime": round(length(pt::text(body)) / 5 / 200)  }}
export type HomeQueryResult = {
  settings:
    | {
        eyebrow: null
        heading: null
        intro: null
      }
    | {
        eyebrow: string | null
        heading: string
        intro: string | null
      }
    | null
  featured: Array<{
    _id: string
    title: string
    slug: string
    summary: string
    publishedDate: string
    featured: true
    tags: Array<string> | null
    featuredImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      _type: 'image'
      lqip: string | null
      dimensions: SanityImageDimensions | null
    }
    authorName: string
    readingTime: number
  }>
  stories: Array<{
    _id: string
    title: string
    slug: string
    summary: string
    publishedDate: string
    featured: boolean | null
    tags: Array<string> | null
    featuredImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      _type: 'image'
      lqip: string | null
      dimensions: SanityImageDimensions | null
    }
    authorName: string
    readingTime: number
  }>
}

// Source: ../web/app/utils/queries.ts
// Variable: storyQuery
// Query: *[_type == "story" && defined(slug.current) && defined(publishedDate) && slug.current == $slug][0]{  _id,    title,    "slug": slug.current,    summary,    publishedDate,    featured,    tags,    featuredImage{      ...,      "lqip": asset->metadata.lqip,      "dimensions": asset->metadata.dimensions    },    "authorName": author->name,    "readingTime": round(length(pt::text(body)) / 5 / 200),  body[]{    ...,    _type == "image" => {      ...,      "lqip": asset->metadata.lqip,      "dimensions": asset->metadata.dimensions    }  },  author->{ name, bio, avatar },  "related": *[_type == "story" && defined(slug.current) && defined(publishedDate) && slug.current != ^.slug.current] | order(publishedDate desc)[0...3]{    _id,    title,    "slug": slug.current,    summary,    publishedDate,    featured,    tags,    featuredImage{      ...,      "lqip": asset->metadata.lqip,      "dimensions": asset->metadata.dimensions    },    "authorName": author->name,    "readingTime": round(length(pt::text(body)) / 5 / 200)  }}
export type StoryQueryResult = {
  _id: string
  title: string
  slug: string
  summary: string
  publishedDate: string
  featured: boolean | null
  tags: Array<string> | null
  featuredImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
    lqip: string | null
    dimensions: SanityImageDimensions | null
  }
  authorName: string
  readingTime: number
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
        lqip: string | null
        dimensions: SanityImageDimensions | null
      }
  >
  author: {
    name: string
    bio: string | null
    avatar: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  }
  related: Array<{
    _id: string
    title: string
    slug: string
    summary: string
    publishedDate: string
    featured: boolean | null
    tags: Array<string> | null
    featuredImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      _type: 'image'
      lqip: string | null
      dimensions: SanityImageDimensions | null
    }
    authorName: string
    readingTime: number
  }>
} | null

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "settings": *[_id == "siteSettings"][0]{ eyebrow, heading, intro },\n  "featured": *[_type == "story" && defined(slug.current) && defined(publishedDate) && featured == true] | order(publishedDate desc)[0...3]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedDate,\n    featured,\n    tags,\n    featuredImage{\n      ...,\n      "lqip": asset->metadata.lqip,\n      "dimensions": asset->metadata.dimensions\n    },\n    "authorName": author->name,\n    "readingTime": round(length(pt::text(body)) / 5 / 200)\n  },\n  "stories": *[_type == "story" && defined(slug.current) && defined(publishedDate)] | order(publishedDate desc){\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedDate,\n    featured,\n    tags,\n    featuredImage{\n      ...,\n      "lqip": asset->metadata.lqip,\n      "dimensions": asset->metadata.dimensions\n    },\n    "authorName": author->name,\n    "readingTime": round(length(pt::text(body)) / 5 / 200)\n  }\n}': HomeQueryResult
    '*[_type == "story" && defined(slug.current) && defined(publishedDate) && slug.current == $slug][0]{\n  _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedDate,\n    featured,\n    tags,\n    featuredImage{\n      ...,\n      "lqip": asset->metadata.lqip,\n      "dimensions": asset->metadata.dimensions\n    },\n    "authorName": author->name,\n    "readingTime": round(length(pt::text(body)) / 5 / 200),\n  body[]{\n    ...,\n    _type == "image" => {\n      ...,\n      "lqip": asset->metadata.lqip,\n      "dimensions": asset->metadata.dimensions\n    }\n  },\n  author->{ name, bio, avatar },\n  "related": *[_type == "story" && defined(slug.current) && defined(publishedDate) && slug.current != ^.slug.current] | order(publishedDate desc)[0...3]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedDate,\n    featured,\n    tags,\n    featuredImage{\n      ...,\n      "lqip": asset->metadata.lqip,\n      "dimensions": asset->metadata.dimensions\n    },\n    "authorName": author->name,\n    "readingTime": round(length(pt::text(body)) / 5 / 200)\n  }\n}': StoryQueryResult
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
